-- ============================================================================
-- 20260914150300 — NEUTRALISÉE
--
-- Cette migration contenait un TRUNCATE … CASCADE de toutes les tables
-- métier (remise à zéro avant livraison). Elle a été exécutée en production
-- le 14/09/2026 : son effet est acquis.
--
-- Un TRUNCATE n'a pas sa place dans une migration : toute nouvelle instance
-- (staging, restauration, base locale) l'aurait rejouée et vidée. Le fichier
-- est conservé sous ce nom pour que l'historique des migrations reste aligné
-- avec `supabase_migrations.schema_migrations`, mais son contenu est vide.
--
-- Le script de remise à zéro vit désormais dans
-- `supabase/scripts/clean_test_data.sql` — à exécuter à la main, une seule
-- fois, dans le SQL Editor.
-- ============================================================================
select 1;
